const strings = {
  name: 'Name:',
  height: 'Height:',
  model: 'Model:',
  mass: 'Mass:',
  skinColors: 'Skin Color:',
  hairColor: 'Hair Color:',
  eyeColor: 'Eye Color:',
  birthYear: 'Birth Year:',
  gender: 'Gender:',
  manufacturer: 'Manufacturer:',
  cost: 'Cost (in credits):',
  length: 'Length:',
  crew: 'Crew:',
  passengers: 'Passengers:',
  cargo: 'Cargo Capacity:',
  consumables: 'Consumables:',
  back: 'GO BACK',
  classification: 'Classification:',
  designation: 'Designation:',
  averageHeight: 'Average height:',
  skinColors: 'Skin Colors:',
  hairColors: 'Hair Colors:',
  averageLifespan: 'Average Lifespan:',
  language: 'language',
  rotation: 'Rotation Period:',
  orbital: 'Orbital Period:',
  diameter: 'Diameter:',
  climate: 'Climate:',
  gravity: 'Gravity',
  terrain: 'Terrain:',
  population: 'Population',
  welcome: 'Welcome to Star Wars',
  gotoFilms: 'GO TO FILMS',
  credits: 'ALL CREDITS GO TO NMCP',
  gotoCharacters: 'Go to Characters',
  gotoPlanets: 'Go to Planets',
  gotoStarships: 'Go to Starships',
  gotoVehicles: 'Go to Vehicles',
  gotoSpecies: 'Go to Species',
};
export default strings;
